version: 0.0
os: linux
files:
  - source: ./cake/templates
    destination: /var/www/html/cake/templates
  - source: ./cake/src
    destination: /var/www/html/cake/src
  - source: ./cake/config
    destination: /var/www/html/cake/config
  - source: ./cake/webroot
    destination: /var/www/html/cake/webroot
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root